### ISSUE TITLE
RangeError: Maximum call stack size exceeded v0.1.2

### ISSUE THREAD

**Issue by mdtanrikulu** [KSDaemon/wampy-cra#17]
Hey there!

I don't know why this happens but I started to get `RangeError: Maximum call stack size exceeded` error shown as below, after dependency update. I rollback to v0.1.1, now everything is fine.

```
RangeError: Maximum call stack size exceeded

      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:17)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      at _typeof (node_modules/wampy-cra/build/wampy-cra.js:3:88)
      ...
```

**Comment by KSDaemon** [comment]
Hmmm.. Interesting... Thanks for pointing out. 
Can you paste how you use it? What versions of wampy do you use?

**Comment by mdtanrikulu** [comment]
Wampy: 6.2.2. It's here;
https://github.com/golemfactory/golem-electron/blob/f517c06d1ae0871042ddbb71144b451f51673310/src/sagas/index.js#L72-L124
